name: CI/CD Pipeline for Backend App

on:
  push:
    branches:
      - main  # Trigger action when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger action for pull requests to the main branch

jobs:
  # Job to set up Python and run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest  # Assuming you're using pytest for testing
